// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/components/Layout/AppMain.vue')['default']
    BarChart: typeof import('./src/components/Charts/BarChart.vue')['default']
    Calendar: typeof import('./src/components/Calendar/index.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    Cascader: typeof import('./src/components/DynamicForm/components/Cascader.vue')['default']
    Checkbox: typeof import('./src/components/DynamicForm/components/Checkbox.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor/index.vue')['default']
    CountChart: typeof import('./src/components/Charts/CountChart.vue')['default']
    DatePicker: typeof import('./src/components/DynamicForm/components/DatePicker.vue')['default']
    DateTable: typeof import('./src/components/Calendar/date-table.vue')['default']
    Demo: typeof import('./src/components/Demo/index.vue')['default']
    DraggableResizableBox: typeof import('./src/components/DraggableResizableBox/index.vue')['default']
    DynamicForm: typeof import('./src/components/DynamicForm/index.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    FullScreenButton: typeof import('./src/components/FullScreenButton/index.vue')['default']
    Input: typeof import('./src/components/DynamicForm/components/Input.vue')['default']
    InputNumber: typeof import('./src/components/DynamicForm/components/InputNumber.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    LazyLoadImg: typeof import('./src/components/LazyLoadImg/index.vue')['default']
    LineChart: typeof import('./src/components/Charts/LineChart.vue')['default']
    LiquidChart: typeof import('./src/components/Charts/LiquidChart.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    MapChart: typeof import('./src/components/Charts/MapChart.vue')['default']
    PieChart: typeof import('./src/components/Charts/PieChart.vue')['default']
    Radio: typeof import('./src/components/DynamicForm/components/Radio.vue')['default']
    RankingChart: typeof import('./src/components/Charts/RankingChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/DynamicForm/components/Select.vue')['default']
    Switch: typeof import('./src/components/DynamicForm/components/Switch.vue')['default']
    TextArea: typeof import('./src/components/DynamicForm/components/TextArea.vue')['default']
    TimePicker: typeof import('./src/components/DynamicForm/components/TimePicker.vue')['default']
    Topbar: typeof import('./src/components/Layout/Topbar.vue')['default']
    Uploader: typeof import('./src/components/DynamicForm/components/Uploader.vue')['default']
    VueCountTo: typeof import('./src/components/VueCountTo/index.vue')['default']
    Waterfall: typeof import('./src/components/Waterfall/index.vue')['default']
  }
}

export {}
